if L1QS_macroPlacement or L1QS_Bindings or L1QS_characterMacros or L1QS_Settings then
return
end
-- You only need to edit this file if you plan on playing on a fresh account
-- Copy paste the contents of the file _Lvl1QuickSetup.lua inside your WTF folder below:

-- TODO WE MAY HAVE PATCHED THE BELOW. WE'LL SEE NEXT TIME WE UPDATE OUR QUICKSTART
-- TODO if we ever run saveAll() again to rewrite our default warrior, add these items (we made a patch to allow items in frames)
-- we have a macro "1 print spells" that you can use to see what is in each action bar
-- below is what the additions we have, make sure you logout of your characters and then put these in the SavedVariables and this one here as well
-- [72] = 6948, -- hearth stone
-- [68] = 117, -- lvl 1 meat

L1QS_macroPlacement = {
["WARRIOR"] = {
6603,
[106] = 818,
[75] = "war rend",
[91] = 72,
[107] = 2383,
[62] = 1160,
[108] = 2259,
[47] = 3274,
[109] = "1 unequip",
[63] = 6673,
[78] = "war overpower",
[94] = 2457,
[110] = "1 charge blink",
[79] = 72,
[48] = 2550,
[64] = "war bloodrage",
[80] = "war blink",
[97] = "1 unequip weapon",
[66] = "warrior hs",
[82] = 2457,
[98] = "1 afk",
[67] = "war sunder",
[83] = 71,
[50] = "RXPTargeting",
[35] = "1 ghetto hearth",
[85] = 6603,
[51] = "1 CritterTarget",
[36] = 818,
[52] = "1 throw",
[73] = 6343,
[89] = 355,
[61] = 26296,
[74] = 1715,
[95] = 71,
[34] = "1 sharpen stone",
[72] = 6948, -- hearth stone
[68] = 117, -- lvl 1 meat
},
}
L1QS_Bindings = {
["WARRIOR"] = {
["SHIFT-5"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-C"] = "MULTIACTIONBAR4BUTTON10",
["CTRL--"] = "MASTERVOLUMEDOWN",
["SHIFT-Z"] = "MULTIACTIONBAR2BUTTON9",
["META-1"] = "INTERACTTARGET",
["SHIFT-I"] = "TOGGLEPETBOOK",
["SHIFT-MOUSEWHEELUP"] = "ACTIONBUTTON11",
["F2"] = "TARGETPARTYMEMBER1",
["SHIFT-X"] = "MULTIACTIONBAR2BUTTON10",
["SHIFT-TAB"] = "TARGETPREVIOUSENEMY",
["BUTTON4"] = "ACTIONBUTTON6",
["LEFT"] = "TURNLEFT",
["CTRL-MOUSEWHEELUP"] = "ACTIONBUTTON12",
["CTRL-PAGEDOWN"] = "COMBATLOGPAGEDOWN",
["SHIFT-6"] = "ACTIONPAGE6",
["SHIFT-3"] = "MULTIACTIONBAR1BUTTON3",
["END"] = "NEXTVIEW",
["F5"] = "TARGETPARTYMEMBER4",
["CTRL-F9"] = "SHAPESHIFTBUTTON9",
["SHIFT-T"] = "MULTIACTIONBAR2BUTTON5",
["MOUSEWHEELDOWN"] = "JUMP",
["PRINTSCREEN"] = "SCREENSHOT",
["SHIFT-BUTTON4"] = "ACTIONBUTTON7",
["'"] = "TOGGLERUN",
["SHIFT-4"] = "MULTIACTIONBAR1BUTTON4",
["PAGEDOWN"] = "CHATPAGEDOWN",
["BUTTON5"] = "ACTIONBUTTON8",
["NUMPADDIVIDE"] = "TOGGLERUN",
["1"] = "ACTIONBUTTON1",
["0"] = "TOGGLEAUTORUN",
["3"] = "ACTIONBUTTON3",
["2"] = "ACTIONBUTTON2",
["5"] = "ACTIONBUTTON5",
["SHIFT-A"] = "MULTIACTIONBAR1BUTTON7",
["CTRL-F5"] = "SHAPESHIFTBUTTON5",
["="] = "CAMERAZOOMIN",
["A"] = "MULTIACTIONBAR1BUTTON6",
["SHIFT-PAGEDOWN"] = "CHATBOTTOM",
["C"] = "TOGGLECHARACTER0",
["B"] = "OPENALLBAGS",
["E"] = "STRAFERIGHT",
["D"] = "MULTIACTIONBAR1BUTTON8",
["G"] = "MULTIACTIONBAR1BUTTON12",
["F"] = "MULTIACTIONBAR1BUTTON10",
["CTRL-F6"] = "SHAPESHIFTBUTTON6",
["H"] = "TOGGLECHARACTER4",
["K"] = "TOGGLECHARACTER1",
["SHIFT-MOUSEWHEELDOWN"] = "TOGGLEAUTORUN",
["M"] = "TOGGLEWORLDMAP",
["SHIFT-BUTTON3"] = "MULTIACTIONBAR2BUTTON12",
["O"] = "TOGGLESOCIAL",
["N"] = "TOGGLETALENTS",
["Q"] = "STRAFELEFT",
["P"] = "TOGGLESPELLBOOK",
["S"] = "MOVEBACKWARD",
["R"] = "MULTIACTIONBAR2BUTTON2",
["U"] = "TOGGLECHARACTER2",
["T"] = "MULTIACTIONBAR2BUTTON4",
["W"] = "MOVEFORWARD",
["V"] = "MULTIACTIONBAR2BUTTON6",
["ESCAPE"] = "TOGGLEGAMEMENU",
["X"] = "SITORSTAND",
["Z"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-F2"] = "TARGETPARTYPET1",
["META-MOUSEWHEELDOWN"] = "MULTIACTIONBAR4BUTTON3",
["ALT-2"] = "CLICK RXPTargetFrame_EnemyButton2:LeftButton",
["CTRL-F3"] = "SHAPESHIFTBUTTON3",
["SHIFT-1"] = "MULTIACTIONBAR1BUTTON1",
["SHIFT-G"] = "MULTIACTIONBAR2BUTTON1",
["SHIFT-D"] = "MULTIACTIONBAR1BUTTON9",
["ALT-4"] = "CLICK RXPTargetFrame_EnemyButton4:LeftButton",
["CTRL-6"] = "BONUSACTIONBUTTON6",
["CTRL-PAGEUP"] = "COMBATLOGPAGEUP",
["F12"] = "TOGGLEBACKPACK",
["SHIFT-F"] = "MULTIACTIONBAR1BUTTON11",
["F11"] = "TOGGLEBAG4",
["CTRL-9"] = "BONUSACTIONBUTTON9",
["F10"] = "TOGGLEBAG3",
["ENTER"] = "OPENCHAT",
["F1"] = "TARGETSELF",
["ALT-1"] = "CLICK RXPTargetFrame_EnemyButton1:LeftButton",
["SPACE"] = "JUMP",
["CTRL-F8"] = "SHAPESHIFTBUTTON8",
["META-4"] = "CLICK RXPTargetFrame_FriendlyButton3:LeftButton",
["HOME"] = "PREVVIEW",
["ALT-Z"] = "TOGGLEUI",
["META-2"] = "CLICK RXPTargetFrame_FriendlyButton1:LeftButton",
["SHIFT-F5"] = "TARGETPARTYPET4",
["CTRL-F1"] = "SHAPESHIFTBUTTON1",
["ALT-3"] = "CLICK RXPTargetFrame_EnemyButton3:LeftButton",
["MOUSEWHEELUP"] = "ACTIONBUTTON10",
["8"] = "CLICK RXPInventory_DeleteJunk:LeftButton",
["META-5"] = "RAIDTARGET4",
["SHIFT-BUTTON5"] = "ACTIONBUTTON9",
["CTRL-F4"] = "SHAPESHIFTBUTTON4",
["CTRL-8"] = "BONUSACTIONBUTTON8",
["4"] = "ACTIONBUTTON4",
["RIGHT"] = "TURNRIGHT",
["CTRL-V"] = "ALLNAMEPLATES",
["TAB"] = "TARGETNEARESTENEMY",
["CTRL-S"] = "TOGGLESOUND",
["F4"] = "TARGETPARTYMEMBER3",
["F9"] = "TOGGLEBAG2",
["CTRL-F10"] = "SHAPESHIFTBUTTON10",
["F8"] = "TOGGLEBAG1",
["SHIFT-F1"] = "TARGETPET",
["SHIFT-R"] = "MULTIACTIONBAR2BUTTON3",
["SHIFT-UP"] = "PREVIOUSACTIONPAGE",
["DOWN"] = "MOVEBACKWARD",
["CTRL-F7"] = "SHAPESHIFTBUTTON7",
["UP"] = "MOVEFORWARD",
["NUMPADPLUS"] = "MINIMAPZOOMIN",
["CTRL-F2"] = "SHAPESHIFTBUTTON2",
["NUMPADMINUS"] = "MINIMAPZOOMOUT",
["J"] = "TOGGLEGUILDTAB",
["SHIFT-SPACE"] = "TOGGLEWORLDSTATESCORES",
["L"] = "TOGGLEQUESTLOG",
["CTRL-7"] = "BONUSACTIONBUTTON7",
["SHIFT-M"] = "TOGGLEBATTLEFIELDMINIMAP",
["CTRL-SHIFT-TAB"] = "TARGETPREVIOUSFRIEND",
["SHIFT-2"] = "MULTIACTIONBAR1BUTTON2",
["SHIFT-F4"] = "TARGETPARTYPET3",
["BUTTON3"] = "MULTIACTIONBAR2BUTTON11",
["CTRL-SHIFT-PAGEDOWN"] = "COMBATLOGBOTTOM",
["CTRL-="] = "MASTERVOLUMEUP",
["F3"] = "TARGETPARTYMEMBER2",
["SHIFT-F3"] = "TARGETPARTYPET2",
["CTRL-0"] = "BONUSACTIONBUTTON10",
["SHIFT-DOWN"] = "NEXTACTIONPAGE",
["CTRL-M"] = "TOGGLEMUSIC",
["INSERT"] = "PITCHUP",
["/"] = "OPENCHATSLASH",
["CTRL-TAB"] = "TARGETNEARESTFRIEND",
["-"] = "CAMERAZOOMOUT",
["META-3"] = "CLICK RXPTargetFrame_FriendlyButton2:LeftButton",
["PAGEUP"] = "CHATPAGEUP",
["SHIFT-V"] = "MULTIACTIONBAR2BUTTON7",
["DELETE"] = "PITCHDOWN",
},
}
L1QS_characterMacros = {
["WARRIOR"] = {
{
"1 2 hand",
132269,
"/run PickupInventoryItem(17) PutItemInBackpack()\n/click MultiBarRightButton11\n/click MultiBarLeftButton12\n",
true,
},
{
"1 afk",
136190,
"/run if LogoutAuto then LogoutAuto:UnregisterAllEvents() LogoutAuto:SetScript(\"OnEvent\", nil) LogoutAuto=nil print(\"Auto logout OFF\") end\n/camp\n",
true,
},
{
"1 attack",
130730,
"/startattack\n",
true,
},
{
"1 blink revert",
132123,
"/run if LogoutAuto then LogoutAuto:UnregisterAllEvents() LogoutAuto:SetScript(\"OnEvent\", nil) LogoutAuto=nil print(\"Auto logout OFF\") end\n",
true,
},
{
"1 charge blink",
132337,
"/run if not LogoutAuto then LogoutAuto = CreateFrame(\"Frame\") LogoutAuto:RegisterEvent(\"PLAYER_CAMPING\") LogoutAuto:SetScript(\"OnEvent\", function() local p=StaticPopup_Visible(\"CAMP\") if p then _G[p..\"Button1\"]:Click() end end) print(\"Auto logout ON\") end\n",
true,
},
{
"1 CritterTarget",
132150,
"/cleartarget\n/targetexact Biletoad\n/targetexact Snake\n/targetexact Adder\n/script SetRaidTarget(\"target\", 4)\n/run Critter_Rotate()",
true,
},
{
"1 equip 2h",
135326,
"/click MultiBarRightButton12 \n",
true,
},
{
"1 first aid",
134400,
"#showtooltip First Aid\n/cast First Aid\n/run local target=\"Wool Bandage\"; for i=1, GetNumTradeSkills() do local name=GetTradeSkillInfo(i); if name==target then CloseTradeSkill(); DoTradeSkill(i); break; end end\n",
true,
},
{
"1 fish",
134400,
"#showtooltip Fishing\n/equip Fishing Pole\n/cast Fishing\n",
true,
},
{
"1 fishing comp",
132162,
"/target riggle bassbait\n",
true,
},
{
"1 follow",
294471,
"/target Bansheego\n/follow\n",
true,
},
{
"1 ghetto hearth",
135746,
"/run InviteUnit(\"abcd\");C_Timer.After(1,function() LeaveParty() end)\n",
true,
},
{
"1 health",
134400,
"#showtooltip\n/use Major Healing Potion\n/use Whipper Root Tuber\n",
true,
},
{
"1 moon icon",
136071,
"/tm 5\n",
true,
},
{
"1 mount",
134400,
"#showtooltip Brown Kodo\n/equip Heavy Linen Gloves\n/equip Carrot on a Stick\n/use Brown Kodo\n",
true,
},
{
"1 print spells",
134400,
"-- prints everything on the action bar and their spell id\n/run for i=1,120 do local t,id=GetActionInfo(i) if t then print(i,GetActionText(i), t,id) end end\n",
true,
},
{
"1 rage belt",
134400,
"/equip Barbaric Belt\n/use Barbaric Belt\n/click MultiBarRightButton10\n",
true,
},
{
"1 sharpen stone",
135248,
"#showtooltip Rough Sharpening Stone\n/use Rough Sharpening Stone\n/use [mainhand] 16\n",
true,
},
{
"1 shield",
132361,
"/click DominosActionButton24\n/click DominosActionButton23\n",
true,
},
{
"1 skull",
132095,
"/script SetRaidTarget(\"target\", 8)\n",
true,
},
{
"1 target",
134400,
"/target prince\n",
true,
},
{
"1 target",
132152,
"/targetexact Yarrog Baneshadow\n/targetlasttarget [dead]\n/startattack\n",
true,
},
{
"1 target",
134400,
"/target [@mouseover,exists]\n",
true,
},
{
"1 throw",
132324,
"/cast [@mouseover,harm,nodead][harm,nodead] Throw\n",
true,
},
{
"1 train",
134400,
"/train\n",
true,
},
{
"1 unequip",
135871,
"/script for i=1,19 do if i ~= 16 and i ~= 18 and i ~= 17 and GetInventoryItemLink(\"player\",i) then PickupInventoryItem(i) PutItemInBackpack() end end\n",
true,
},
{
"1 unequip weapon",
132402,
"/run for s=16,17 do if GetInventoryItemLink(\"player\",s) then PickupInventoryItem(s) PutItemInBackpack() end end ClearCursor()\n",
true,
},
{
"1 venture",
134400,
"/target venture co. merc\n/tm 4\n",
true,
},
{
"1 weapons",
132147,
"/equipslot 16 Baron's Scepter\n/equipslot 17 Butcher's Slicer\n",
true,
},
{
"druid bear",
132276,
"#showtooltip\n/cancelaura [stance:3] Cat Form; [stance:2] Aquatic Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance]  Dire Bear Form\n/stopcasting\n/cast Bear Form\n",
true,
},
{
"druid cat",
132115,
"#showtooltip Cat Form\n/cancelaura [stance:1] Dire Bear Form; [stance:2] Aquatic Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance] Cat Form\n/stopcasting\n/cast Cat Form\n",
true,
},
{
"druid dash",
134400,
"#showtooltip Dash\n/cancelaura [stance:1] Dire Bear Form;  [stance:2] Aquatic Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance] Cat Form\n/cast Dash\n",
true,
},
{
"druid ht",
134400,
"#showtooltip Healing Touch\n/cancelaura [stance:1] Bear Form;  [stance:2] Aquatic Form; [stance:3] Cat Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast Healing Touch\n",
true,
},
{
"druid moonfire",
136096,
"#showtooltip moonfire\n/startattack\n/cast moonfire\n/startattack\n",
true,
},
{
"druid prowl",
132089,
"#showtooltip Prowl\n/cancelaura [stance:1] Bear Form;  [stance:2] Aquatic Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance] Cat Form\n/cast Prowl\n",
true,
},
{
"druid rej",
136085,
"#showtooltip Regrowth\n/cancelaura [stance:1] Bear Form;  [stance:2] Aquatic Form; [stance:3] Cat Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast Regrowth\n",
true,
},
{
"druid sunfire",
134400,
"#showtooltip Sunfire\n/startattack\n/cast [form:1/3,@mouseover,harm,nodead] [form:1/3] Moonfire(Rank 1); [@mouseover,harm,nodead] [] Sunfire\n/startattack\n",
true,
},
{
"druid swim",
134400,
"#showtooltip Aquatic Form\n/cancelaura [stance:1] Dire Bear Form; [stance:3] Cat Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance] Aquatic Form\n/stopcasting\n/cast Aquatic Form\n",
true,
},
{
"druid swipe",
134400,
"#showtooltip\n/startattack\n/cast Swipe\n",
true,
},
{
"druid target",
136096,
"/target Serena\n/cast Moonfire\n/startattack\n",
true,
},
{
"druid travel",
134400,
"#showtooltip Travel Form\n/cancelaura [stance:1] Dire Bear Form; [stance:2] Aquatic Form; [stance:3] Cat Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast [nostance] Travel Form\n/stopcasting\n/cast Travel Form\n",
true,
},
{
"druid warstomp",
132368,
"#showtooltip War Stomp\n/cancelaura [stance:1] Dire Bear Form;  [stance:2] Aquatic Form; [stance:3] Cat Form; [stance:4] Travel Form; [stance: 5] Moonkin Form <or Tree of Life>\n/cast War Stomp\n",
true,
},
{
"druid wrath",
136006,
"#showtooltip wrath\n/startattack\n/cast wrath\n",
true,
},
{
"hunt flanking",
134400,
"#showtooltip\n/startattack\n/cast Flanking Strike\n",
true,
},
{
"hunter attack",
135493,
"#showtooltip Auto Shot\n/target [@mouseover,exists,nodead]\n/cast !Auto Shot\n",
true,
},
{
"hunter growl",
132270,
"#showtooltip\n/cast Growl\n",
true,
},
{
"hunter passive",
132311,
"/petpassive\n",
true,
},
{
"hunter petattack",
135645,
"#showtooltip\n/petattack [@mouseover,harm][]\n",
true,
},
{
"hunter petdef",
132110,
"/petdefensive\n",
true,
},
{
"hunter raptor",
134400,
"#showtooltip Raptor Strike\n/target [@mouseover,exists,nodead]\n/cast Raptor Strike\n/startattack\n",
true,
},
{
"rogue garrote",
134400,
"#showtooltip Garrote\n/cast Pick Pocket\n/cast Garrote\n",
true,
},
{
"rogue gouge",
134400,
"#showtooltip\n/castsequence reset=3 Gouge, Linen Bandage\n",
true,
},
{
"rogue Pick",
132090,
"#showtooltip Backstab\n/cast Pick Pocket\n/cast Backstab\n",
true,
},
{
"rogue pickpock",
134400,
"#showtooltip Pick Pocket\n/targetenemy\n/cast Pick Pocket\n",
true,
},
{
"rogue sinister",
134400,
"#showtooltip Sinister Strike\n/startattack\n/cast Sinister Strike\n",
true,
},
{
"RXPTargeting",
132150,
"/targetexact Voodoo Trolls\n/targetexact Captain Flat Tusk\n/targetexact Makasgar\n/targetexact Felweaver Scornn\n/targetexact Zalazane\n/targetexact Warlord Kolkanis\n/targetexact Gazz'uz\n/targetexact Mottled Boar\n/targetlasttarget [dead]",
true,
},
{
"shaman",
136052,
"#showtooltip\n/cast [@mouseover,help,nodead][help,nodead][@player] Healing Wave\n",
true,
},
{
"shaman attack",
134400,
"#showtooltip\n/cast Earth Shock\n/startattack\n",
true,
},
{
"war battle shout",
134400,
"#showtooltip Battle Shout\n/cast Battle Shout\n",
true,
},
{
"war blink",
134400,
"#showtooltip\n/startattack\n/cast Charge\n/camp\n/click StaticPopup1Button1\n",
true,
},
{
"war bloodrage",
134400,
"#showtooltip Bloodrage\n/cast Bloodrage\n/cancelaura Bloodrage\n",
true,
},
{
"war bloodthirst",
134400,
"#showtooltip\n/startattack\n/cast Bloodthirst\n",
true,
},
{
"war cleave",
134400,
"#showtooltip Cleave\n/cast Cleave\n/startattack\n/stopcasting\n",
true,
},
{
"war intercept",
134400,
"#showtooltip\n/startattack\n/cast Intercept\n/camp\n/click StaticPopup1Button1\n",
true,
},
{
"war intimidating",
134400,
"#showtooltip\n/cleartarget [dead][help]\n/targetenemy [noexists]\n/stopattack\n/cast intimidating shout\n",
true,
},
{
"war mortal",
134400,
"#showtooltip\n/startattack\n/cast Mortal Strike\n",
true,
},
{
"war overpower",
134400,
"#showtooltip overpower\n/startattack\n/cast [nostance:1] Battle Stance\n/cast Overpower\n",
true,
},
{
"war rend",
134400,
"#showtooltip\n/cast Rend\n/startattack\n",
true,
},
{
"war retal",
134400,
"#showtooltip retaliation\n/startattack\n/cast [nostance:1] Battle Stance\n/cast Retaliation\n",
true,
},
{
"war revenge",
134400,
"#showtooltip revenge\n/startattack\n/cast [nostance:2] Defensive Stance\n/cast Revenge\n",
true,
},
{
"war shield block",
134400,
"#showtooltip Shield Block\n/cast [stance:3] Defensive Stance\n/click MultiBarRightButton11\n/click MultiBarLeftButton11 \n/cast Shield Block\n",
true,
},
{
"war shield wall",
132362,
"#showtooltip Shield Wall\n/cast [stance:3] Defensive Stance\n/click DominosActionButton24\n/click DominosActionButton23\n/cast Shield Wall\n",
true,
},
{
"war shieldbash",
134400,
"#showtooltip \n/cast [stance:3] Pummel\n/click [nostance:3] DominosActionButton24\n/click [nostance:3] DominosActionButton23\n/use [nostance:3][@mouseover, exists] Shield Bash ; Shield Bash\n",
true,
},
{
"war stance",
134400,
"#showtooltip\n/cast [stance:2] Berserker Stance; Defensive Stance\n",
true,
},
{
"war sunder",
134400,
"#showtooltip\n/cast Sunder Armor\n/startattack\n",
true,
},
{
"war ww",
134400,
"#showtooltip\n/cast Whirlwind\n/startattack\n",
true,
},
{
"warrior hs",
132282,
"#showtooltip Heroic Strike\n/startattack\n/cast Heroic Strike\n/stopcasting\n",
true,
},
{
"warrior rage pot",
134400,
"#showtooltip\n/cast blood fury\n",
true,
},
{
"warrior shield",
132110,
"/click MultiBarRightButton11\n/click MultiBarLeftButton11 \n",
true,
},
},
}
L1QS_Settings = {
["HUNTER"] = {
},
["WARRIOR"] = {
["RXPDB"] = {
["notifyOnTargetUpdates"] = true,
["showTargetingOnProximity"] = true,
["showUnusedGuides"] = true,
["enableTrainerAutomation"] = true,
["enableItemUpgradesAH"] = true,
["enableEnemyMarking"] = true,
["compareTotalTimeSplit"] = true,
["hardcore"] = true,
["enableMobMarking"] = true,
["worldMapPinScale"] = 1,
["enableAddonIncompatibilityCheck"] = true,
["anchorOrientation"] = "top",
["vendorTreasurePinScale"] = 0.8,
["hightlightTalentPlan"] = true,
["enableQuestChoiceRecommendation"] = true,
["activeTargetScale"] = 1,
["enableTips"] = true,
["season"] = 0,
["enableVendorTreasure"] = true,
["textBuyColor"] = "FF0E8312",
["checkVersions"] = true,
["distanceBetweenPins"] = 1,
["enableTracker"] = true,
["enableEmergencyActions"] = true,
["enableBindAutomation"] = true,
["upcomingTalentCount"] = 60,
["previewTalents"] = true,
["xprate"] = 1,
["notifyOnRares"] = true,
["worldMapPinBackgroundOpacity"] = 0.35,
["alwaysSendBranded"] = true,
["enablelevelSplits"] = true,
["showJunkIcon"] = true,
["enableXpStepSkipping"] = true,
["guideFontSize"] = 9,
["enableAutomaticXpRate"] = true,
["emergencyThreshold"] = 0.2,
["enableGossipAutomation"] = true,
["drowningThreshold"] = 0.2,
["enableQuestRewardAutomation"] = true,
["enableQuestChoiceGoldRecommendation"] = true,
["levelSplitsOpacity"] = 0.9,
["enableLevelingReportInspections"] = true,
["windowScale"] = 0.75,
["textLootColor"] = "FF00BCD4",
["levelSplitsHistory"] = 10,
["enableTargetingFlash"] = true,
["activeTheme"] = "Default",
["soundOnFind"] = 3175,
["itemUpgradeSpec"] = "Warrior",
["enableQuestChoiceAutomation"] = true,
["arrowScale"] = 1,
["enableFPAutomation"] = true,
["chromieTime"] = "auto",
["soundOnFindChannel"] = "Master",
["numMapPins"] = 7,
["showFlightTimers"] = true,
["enableLevelUpAnnounceGroup"] = true,
["shareQuests"] = true,
["batchSize"] = 6,
["macroAnnounced"] = true,
["frameHeight"] = 125.0000534057617,
["enableBetaFeatures"] = true,
["compareNextLevelSplit"] = true,
["scanForRares"] = true,
["openTrackerReportOnCharOpen"] = false,
["enableEmergencyIconAnimations"] = true,
["arrowText"] = 9,
["textFriendlyColor"] = "FF00FF25",
["textWarnColor"] = "FFFCDC00",
["textPickColor"] = "FFDB2EEF",
["enableDrowningWarning"] = true,
["enableTargetAutomation"] = true,
["levelSplitsFontSize"] = 11,
["enableEnemyTargeting"] = true,
["enableGroupQuests"] = true,
["enableFriendlyTargeting"] = true,
["autoDiscardItems"] = true,
["showEnabled"] = true,
["enableMinimapButton"] = true,
["enableTargetMacro"] = true,
["showDangerousMobsMap"] = true,
["enableTalentGuides"] = true,
["textEnemyColor"] = "FFFF5722",
["enableWorldMapButton"] = true,
["enableFlyStepAnnouncements"] = true,
["flashOnFind"] = true,
["rightClickJunk"] = true,
["enableDrowningWarningSound"] = true,
["enableThemeLiveReload"] = true,
["enableTargetMarking"] = true,
["enableLevelUpAnnounceSolo"] = true,
["enableDrowningScreenFlash"] = true,
["activeItemsScale"] = 1,
["showDangerousUnitscan"] = true,
["autoSellJunk"] = true,
["enableQuestAutomation"] = true,
["phase"] = 6,
["enableItemUpgrades"] = true,
},
["RXPframes"] = {
["RXPItemFrame"] = {
"BOTTOM",
false,
"BOTTOM",
-259.9508972167969,
200.4445648193359,
},
["RXPFrame"] = {
"BOTTOMLEFT",
false,
"BOTTOMLEFT",
9.167415618896484,
129.9904327392578,
},
["RXPTargetFrame"] = {
"CENTER",
false,
"CENTER",
-269.8402404785156,
-167.4954223632813,
},
},
},
["HSbatch"] = 9.996,
["Orc"] = {
},
["Gnome"] = {
},
["Troll"] = {
["currentGuideName"] = "fast_as_fuck_boi",
["currentGuideGroup"] = "troll_lvl10_speedrun",
},
["Tauren"] = {
},
["DRUID"] = {
},
["Guidelime"] = {
},
}
